name: "Build and Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Install Nix
      - uses: cachix/install-nix-action@v25

      - name: Build
        run: |
          nix build --option substituters 'https://cache.nixos.org'

      - name: Upload to Cachix
      - uses: cachix/cachix-action@v15
        with:
          name: xache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: result/bin/*
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
